Repository cybertec-postgresql/pg_timetable, pull requests merged in 2019-10, with the labels that each got.

#49 closes #45
  Dockerfile
Labels: CI

#53 Make samples executable by any client. Fix issues. Prettify code
  samples/BasicSQL.sql
  samples/Chain.sql
  samples/CronStyle.sql
  samples/Download.sql
  samples/Log.sql
  samples/Mail.sql
  samples/ManyTasks.sql
  samples/NoOp.sql
  samples/RemoteDB.sql
  samples/Shell.sql
  samples/Sleep.sql
Labels: enhancement

#60 Task functions
  internal/pgengine/access.go
  internal/pgengine/bootstrap.go
  internal/pgengine/pgengine_test.go
  internal/pgengine/transaction.go
  internal/scheduler/scheduler.go
  internal/scheduler/shell.go
  internal/tasks/tasks.go
  samples/Download.sql
  samples/Shell.sql
  sql/tasks.sql
Labels: critical, documentation, enhancement

#64 copy sql directory from building step
  Dockerfile
Labels: CI, bug
