Repository cybertec-postgresql/pg_timetable, pull requests merged in 2020-02, with the labels that each got.

#85 Fixes #83
  internal/cmdparser/cmdparser.go
  internal/pgengine/bootstrap.go
Labels: bug

#91 Embed SQL statements in binary
  .github/workflows/release.yml
  .gitignore
  .goreleaser.yml
  README.md
  internal/pgengine/bootstrap.go
  internal/pgengine/pgengine_test.go
  internal/pgengine/sql_ddl.go
  internal/pgengine/sql_job_functions.go
  internal/pgengine/sql_json_schema.go
  internal/pgengine/sql_tasks.go
  main.go
  sql/timetable.pdd
  timetable_schema.png
Labels: enhancement

#92 Improve release and test actions
  .github/workflows/build.yml
  .github/workflows/release.yml
  .goreleaser.yml
Labels: CI, enhancement

#97 Add test cases for samples scripts
  internal/pgengine/pgengine_test.go
  samples/Shell.sql
Labels: CI, test

#95 Command line parameter --no-shell-tasks added
  internal/cmdparser/cmdparser.go
  internal/pgengine/bootstrap.go
  internal/scheduler/scheduler.go
Labels: enhancement, priority
