Repository cybertec-postgresql/pg_timetable, pull requests merged in 2021-01, with the labels that each got.

#184 [+] Disable tasks on a REPLICA node
  go.mod
  go.sum
  internal/pgengine/access.go
  internal/pgengine/bootstrap.go
  internal/pgengine/migration.go
  internal/pgengine/sql_ddl.go
  internal/scheduler/chain.go
  internal/scheduler/interval_chain.go
  internal/scheduler/scheduler.go
Labels: enhancement

#186 Usage examples – make them work
  README.md
Labels: documentation

#196 Add abort chain machinery
  .github/workflows/build.yml
  internal/pgengine/access.go
  internal/pgengine/access_test.go
  internal/pgengine/bootstrap.go
  internal/pgengine/log.go
  internal/pgengine/migration.go
  internal/pgengine/notification.go
  internal/pgengine/notification_test.go
  internal/pgengine/sql_ddl.go
  internal/pgengine/sql_job_functions.go
  internal/scheduler/chain.go
  internal/scheduler/chain_test.go
  internal/scheduler/interval_chain.go
  internal/scheduler/scheduler.go
  main.go
Labels: enhancement

#199 [*] remove push trigger, enable pull_request and workflow_dispatch only
  .github/workflows/build.yml
Labels: CI
