Repository cybertec-postgresql/pg_timetable, pull requests merged in 2022-04, with the labels that each got.

#409 [-] fix failed `Update Docker` workflow, closes #408
  .github/workflows/docker.yml
  Dockerfile
Labels: bug, CI

#414 [-] fix "cannot fetch chains if `chain.timeout` field is NULL", fixes #413
  internal/pgengine/access.go
Labels: bug

#422 [+] bump `golangci/golangci-lint-action` to `v3`, closes #421
  .github/workflows/build.yml
  go.mod
  go.sum
Labels: enhancement

#424 [+] trim possible leading or trailing white space from the command
  internal/scheduler/shell.go
Labels: enhancement

#425 [+] docs: clarify how external commands are called
  docs/components.rst
Labels: documentation

#430 [+] add `psql` client to the Docker image by default, closes #429
  Dockerfile
Labels: enhancement
