Repository cybertec-postgresql/pg_timetable, pull requests merged in 2023-07, with the labels that each got.

#587 [+] add support for goreleaser v1.19, fixes #586
  .github/workflows/build.yml
  .goreleaser.yml
Labels: bug, github_actions

#585 [*] refactor autonomous and remote tasks execution, fixes #584
  .golangci.yml
  go.mod
  go.sum
  internal/pgengine/access.go
  internal/pgengine/access_test.go
  internal/pgengine/bootstrap.go
  internal/pgengine/pgengine_test.go
  internal/pgengine/transaction.go
  internal/pgengine/transaction_test.go
  internal/pgengine/types.go
  internal/scheduler/chain.go
  internal/scheduler/chain_test.go
  internal/scheduler/scheduler_test.go
  main.go
  samples/ClientMessages.sql
Labels: bug, enhancement

#591 [+] add a Sphinx `conf.py` file to documentation, fixes #590
  docs/conf.py
Labels: bug, documentation

#589 [-] reset session before returning connection to the pool
  internal/pgengine/bootstrap.go
  internal/pgengine/copy_test.go
Labels: bug
